server:
  port: 8090

spring:
  application:
    name: eureka-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: 127.0.0.1:8090
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000

security:
  basic:
    enabled: false
  user:
    name: user
    password: 1234
